export const GET_DOCKER_COMPOSE_DIR = 'get-docker-compose-dir'
export const GET_DOCKER_COMPOSE_DIR_REPLY = 'get-docker-compose-dir-reply'
export const SELECT_DOCKER_COMPOSE_DIR = 'select-docker-compose-dir'
export const SELECT_DOCKER_COMPOSE_DIR_REPLY = 'select-docker-compose-dir-reply'
export const DOCKER_COMPOSE_CMD = 'docker-compose-command'
export const DOCKER_COMPOSE_CMD_REPLY = 'docker-compose-command-reply'
